### ISSUE TITLE
点开新闻报错

### ISSUE THREAD

**Issue by j-waiting-for** [XeonKHJ/InkingNewstand#13]
新闻的原网站无法连接时程序报错
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Object reference not set to an instance of an object.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at AngleSharp.TextSource.ExpandBuffer(Int64 size)
   at AngleSharp.TextSource.ReadCharacter()
   at AngleSharp.Parser.BaseTokenizer.AdvanceUnsafe()
   at AngleSharp.Parser.Html.HtmlTokenizer.Get()
   at AngleSharp.Parser.Html.HtmlDomBuilder.Parse(HtmlParserOptions options)
   at AngleSharp.Parser.Html.HtmlParser.Parse(Stream source)
   at SmartReader.Reader.GetArticle()
   at InkingNewstand.Utilities.HtmlConverter.<>c__DisplayClass2_0.<ExtractReadableContent>b__0() in C:\Users\FireM\Source\Repos\InkingNewstand\InkingNewstand.Utilities\HtmlConverter.cs:line 51
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

内部异常 1:
NullReferenceException: Object reference not set to an instance of an object.

**Comment by XeonKHJ** [comment]
已经添加了异常处理。
