### ISSUE TITLE
在添加报纸后自动刷新新闻会在Feeds更新到数据库时出现一下错误

### ISSUE THREAD

**Issue by XeonKHJ** [XeonKHJ/InkingNewstand#34]
> System.InvalidOperationException
>   HResult=0x80131509
>   Message=The instance of entity type 'NewsPaper_Feed' cannot be tracked because another instance with the same key value for {'FeedId', 'NewsPaperId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
>   Source=Microsoft.EntityFrameworkCore
>   StackTrace:
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
>    at Microsoft.EntityFrameworkCore.DbContext.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
>    at InkingNewsstand.Classes.NewsPaper.<SaveAsync>d__24.MoveNext() in D:\Dev\Repos\InkingNewsstand\InkingNewsstand\Classes\NewsPaper.cs:line 315
>

**Comment by XeonKHJ** [comment]
原来是当用EF中当用`var NewsPaper_Feeds = db.NewsPaper_Feeds.ToList()`时，EF会一直追踪`Feed.NewsPaper_Feeds`，具体关系牵得太乱，改用每次重新添加各`Feed.NewsPaper_Feeds`即可。鉴于Update方法中说仅仅会修改和添加，那么就不用太在意`Feed.NewsPaper_Feeds`到底完整不完整，只要把这次要修改的添加到`Feed.NewsPaper_Feeds`里面，并用`db.Feeds.UpdateRange(Feed.NewsPaper_Feeds)`即可更新成功。
